version: '3.0'
services:
    php:
      container_name: c-php8
      build:
        context: ./
        dockerfile: ./docker/Dockerfile
      volumes:
        - ./:/var/www/html
        - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      environment:
        - PHP_IDE_CONFIG=serverName=localhost
      ports:
        - 7777:80


